name: Fetch Releases JSON
description: Fetches the _releases.json file to the current repository.

inputs:
  image-name:
    description: 'OCI image name to fetch the releases JSON for'
    required: true
  releases-branch:
    description: 'Branch where the _releases.json file is located'
    required: false
    default: '_releases'
  directory:
    description: 'Directory where the _releases branch of the OCI Factory is checked out'
    default: oci-factory-releases



runs:
  using: "composite"
  steps:
    - name: Fetch _releases.json
      uses: actions/checkout@v4
      with:
        repository: canonical/oci-factory
        path: ${{ inputs.directory }}
        ref: ${{ inputs.releases-branch }}

    - name: Copy _releases.json
      shell: bash
      run: |
        bash .github/actions/fetch-releases-json/copy-releases-files.sh '${{ inputs.image-name }}' '${{ inputs.directory }}'
