version: 1
# --- OVERVIEW INFORMATION ---
application: prometheus-pushgateway
description: >
  The Prometheus Pushgateway allows ephemeral and batch jobs to expose their
  metrics to Prometheus. Read more on the 
  [prometheus pushgateway repository](https://github.com/prometheus/pushgateway).
# --- USAGE INFORMATION ---
docker:
  parameters:
    - -p 9091:9091
  access: Access your Pushgateway instance at `http://localhost:9091`.
parameters:
  - type: -e
    value: 'TZ=UTC'
    description: Timezone.
  - type: -p
    value: '9091:9091'
    description: Expose the Pushgateway on `localhost:9091`.
debug:
  text: |
    ### Debugging
    
    To debug the container:

    ```bash
    docker logs -f pushgateway-container
    ```

    To get an interactive shell:

    ```bash
    docker exec -it pushgateway-container /bin/bash
    ```
