version: 2
application: prometheus-pushgateway
description: |
  The Prometheus Pushgateway allows ephemeral and batch jobs to expose their
  metrics to Prometheus.
website: https://github.com/prometheus/pushgateway
issues: https://github.com/canonical/prometheus-pushgateway-rock/issues
source-code: https://github.com/canonical/prometheus-pushgateway-rock

docker:
  parameters: >-
    -p 9091:9091
  run_conclusion: |
    Access the Pushgateway instance at `http://localhost:9091`.

config:
  TZ:
    type: env
    description: Timezone.
    default: 'UTC'
  '`-p <port>:9091`':
    type: port
    description: Exposes the container's port `9091` on the host's `<port>`.
