version: 2
upload:
  - source: canonical/prometheus-pushgateway-rock
    commit: e5bd052a1e9252469dd5df5db2e3bd9f45af8e9d
    directory: 1.11.3
    release:
      1-26.04:
        end-of-life: '2026-09-07T00:00:00Z'
        risks:
          - edge
      1.11-26.04:
        end-of-life: '2026-09-07T00:00:00Z'
        risks:
          - edge
