version: 2
upload:
  - source: canonical/prometheus-pushgateway-rock
    commit: d2dea0d6b1f7138c43058367831882f9b8b0a55b
    directory: 1.11.2
    release:
      1-26.04:
        end-of-life: '2026-08-11T00:00:00Z'
        risks:
          - stable
      1.11-26.04:
        end-of-life: '2026-08-11T00:00:00Z'
        risks:
          - stable
