name: Git Checkout
description: 'Checkout action supporting both github and non github repositories.'


inputs:
  repository:
    description: 'Github repository in the format owner/repo or external http(s) URL'
    required: true
  ref:
    description: 'The branch, tag or SHA to checkout'
    default: ''
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    default: '.'
  submodules: 
    description: 'Whether to checkout submodules. true|false|recursive according to actions/checkout@v4'
    default: 'false'
  token:
    description: "Github token for pulling from private repositories"
    default: ''
    required: false
  lfs: 
    description: 'Whether to pull Git LFS files.'
    default: 'false'
    required: false

runs:
  using: "composite" 
  steps:

    # Note: We skip setup-python here because there is no available Python release
    # for architectures other than amd64 and arm64 from GitHub actions/setup-python.
    # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

    - name: Checkout
      shell: bash
      run: |
        
        # If URL lacks the protocol, assume it is a github repo 
        git_url="$(python3 ./src/shared/source_url.py "${{ inputs.repository }}")"

        # if a token is provided, use it
        if ! [[ -z "${{ inputs.token }}" ]]; then
          protocol=$(echo "$git_url" | grep -oE '^[a-zA-Z]+://')
          git_url="${git_url/${protocol}/${protocol}${{ inputs.token }}@}"
        fi

        # create repo path relative to GITHUB_WORKSPACE as per actions/checkout@v4
        repo_path="$GITHUB_WORKSPACE/${{ inputs.path }}"

        # clone the repo and cd into it
        git clone $git_url "$repo_path"
        cd "$repo_path"

        # checkout the correct ref
        git config advice.detachedHead false
        git checkout ${{ inputs.ref }}
        
        # and update sub modules if required
        if ${{ inputs.submodules == 'true' || inputs.submodules == 'recursive' }}
        then
          git submodule update ${{ inputs.submodules == 'recursive' && '--recursive' || '' }}
        fi

        # pull lfs files if required
        if ${{ inputs.lfs == 'true' }}
        then
          git lfs pull
        fi
