name: Parse Build Trigger
description: |
  Parses the build trigger file and sets the output variables.

inputs:
  build-trigger-file:
    description: The path to the build trigger file.
    required: true
  image-dirs:
    description: Comma-separated directories where the images are to be built.
    required: false
    default: ""
    # For example: "mock-rock/1.0,mock-rock/1.2"

outputs:
  build_matrix:
    description: The build matrix as a JSON string.
    value: ${{ steps.parse-build-trigger.outputs.build-matrix }}

runs:
  using: "composite"
  steps:
    - name: Get Workflow Version
      id: workflow-version
      uses: canonical/get-workflow-version-action@v1
      with:
        repository-name: canonical/oci-factory
        file-name: Test-Rock.yaml
        github-token: ${{ secrets.host-github-token }}

    - name: Cloning OCI Factory
      uses: actions/checkout@v4
      with:
        repository: canonical/oci-factory
        ref: ${{ steps.workflow-version.outputs.sha }}
        fetch-depth: 1
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Parse Build Trigger
      id: parse-build-trigger
      shell: bash
      run: |
        python3 -m src.image.parse_image_build_trigger \
          --image-trigger "${{ inputs.build-trigger_file }}" \
          --image-dirs "${{ inputs.image-dirs }}"
