version: 2

application: nginx-prometheus-exporter
description: |
  Nginx prometheus-exporter is a Prometheus exporter for Nginx.
  Read more in the [official documentation](https://github.com/nginx/nginx-prometheus-exporter).
  Please note that this repository holds a rock instead of a Dockerfile-based image.
  As such, the entrypoint is Pebble.
  Read more in the [Rockcraft docs](https://canonical-rockcraft.readthedocs-hosted.com/en/latest/).
website: https://github.com/nginx/nginx-prometheus-exporter
issues: https://github.com/canonical/nginx-prometheus-exporter-rock/issues
source-code: https://github.com/canonical/nginx-prometheus-exporter-rock

docker:
  parameters: >-
    -p 9113:9113
  run_conclusion: |
    The exporter starts and exposes Prometheus metrics on port 9113.
    Access the metrics endpoint at http://localhost:9113/metrics.

config:
  TZ:
    type: env
    description: Timezone.
    default: 'UTC'
  '`-p <port>:9113`':
    type: port
    description: Expose port 9113 on the host.
