version: 2
upload:
  - source: canonical/nginx-prometheus-exporter-rock
    commit: cbc710cbf31eecdb37e1e8cc24769a3a75e34fe3
    directory: 1.4.2
    release:
      1.4-26.04:
        end-of-life: '2026-08-11T00:00:00Z'
        risks:
          - stable
