version: 2
upload:
  - source: canonical/nginx-prometheus-exporter-rock
    commit: 617e925a01c601f9740a1ef4d6b1765f02214300
    directory: 1.5.1
    release:
      1-26.04:
        end-of-life: '2026-08-11T00:00:00Z'
        risks:
          - stable
      1.5-26.04:
        end-of-life: '2031-05-01T00:00:00Z'
        risks:
          - stable
