#cloud-config

# Based on the instructions from https://microk8s.io/docs/install-proxy
write_files:
  - path: /etc/environment
    content: |
      HTTPS_PROXY=http://squid.internal:3128
      HTTP_PROXY=http://squid.internal:3128
      NO_PROXY=10.0.0.0/8,192.168.0.0/16,127.0.0.1,172.16.0.0/16
      https_proxy=http://squid.internal:3128
      http_proxy=http://squid.internal:3128
      no_proxy=10.0.0.0/8,192.168.0.0/16,127.0.0.1,172.16.0.0/16
    append: true
  - path: /home/ubuntu/.ssh/authorized_keys
    content: |
      ${custom_ssh_pub_key}
    append: true

# Based on the instructions from
# https://juju.is/docs/juju/get-started-with-juju#heading--prepare-your-cloud
runcmd:
  - set -ex
  - snap install microk8s --channel 1.25-strict/stable
  - usermod -a -G snap_microk8s ubuntu
  - mkdir -p /home/.kube
  - chown -f -R ubuntu /home/ubuntu
  - microk8s start
  - microk8s status
  - microk8s enable hostpath-storage dns
  - snap alias microk8s.kubectl kubectl
  - ${clusterforming_cmd}
