name: "Upload Rock"
description: "Uploads an OCI artifact to a container registry"
inputs:
  artifact_name:
    description: "The name of the artifact to download"
    required: true
    type: string
  name:
    description: "The name of the image to upload. This should include the namespace if applicable."
    required: true
    type: string
  tags:
    description: "The tags to use for the image"
    required: true
    type: string
  registry:
    description: "The container registry URL"
    required: true
    type: string
  username:
    description: "The username for the container registry"
    required: true
  password:
    description: "The password for the container registry"
    required: true
  run-id:
    description: "The id of the workflow run where the desired download artifact was uploaded from."
  github-token:
    description: "The github token needed for downloading the artifact from a different repository or workflow run."
  decrypt-passphrase:
    description: "The passphrase for the artifact if it is encrypted."
outputs:
  digest:
    description: "The digest of the uploaded image"
    value: ${{ steps.meta.outputs.digest }}

runs:
  using: "composite"
  steps:
    - name: Download Rock
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        run-id: ${{ inputs.run-id }}
        github-token: ${{ inputs.github-token }}
    
    - name: Decrypt Rock
      if: ${{ inputs.decrypt-passphrase }}
      uses: canonical/oci-factory/.github/actions/crypt-artifact@feat/decrypt-before-upload
      with:
        mode: decrypt
        passphrase: ${{ inputs.decrypt-passphrase }}
        input-path: ${{ inputs.artifact_name }}*
        output-path: ${{ inputs.artifact_name }}
        preserve-original: false

    - name: Get Metadata
      id: meta
      shell: bash
      run: |
        docker run --rm \
          -v $PWD:/workdir -w /workdir \
          "quay.io/skopeo/stable:v1.20.0" \
          inspect oci-archive:${{ inputs.artifact_name }} > metadata.json

        digest="$(cat metadata.json | jq -r .Digest)"
        echo "digest=$digest" >> $GITHUB_OUTPUT

    - name: Upload Rock to Registry
      shell: bash
      run: |
        for tag in ${{ inputs.tags }}; do
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          -v $PWD:/workdir -w /workdir \
          "quay.io/skopeo/stable:v1.20.0" \
          copy \
          --dest-username "${{ inputs.username }}" \
          --dest-password "${{ inputs.password }}" \
          --multi-arch all \
          --preserve-digests \
          oci-archive:${{ inputs.artifact_name }} \
          docker://${{ inputs.registry }}/${{ inputs.name }}:$tag
        done
