version: 1
# --- OVERVIEW INFORMATION ---
repo: prometheus
description: >
  Prometheus is a systems and service monitoring system. It collects metrics
  from configured targets at given intervals, evaluates rule expressions,
  displays the results, and can trigger alerts if some condition is observed
  to be true. Read more on the [prometheus website](https://prometheus.io/).
# --- USAGE INFORMATION ---
docker:
  parameters:
    - -p 9090:9090
  access: Access your Prometheus instance at `http://localhost:9090`.
parameters:
  - type: -p
    value: '9090:9090'
    description: Expose Prometheus on `localhost:9090`.
