version: 1
upload:
  - source: canonical/prometheus-rock
    commit: c7696b18c348b3a2831d13253586b38d971966dc
    directory: 3.11.1
    release:
      3-24.04:
        end-of-life: '2026-07-11T00:00:00Z'
        risks:
          - stable
      3.11-24.04:
        end-of-life: '2026-07-11T00:00:00Z'
        risks:
          - stable
      3.11.1-24.04:
        end-of-life: '2026-04-10T00:00:00Z'
        risks:
          - stable
