version: 2
upload:
  - source: canonical/prometheus-rock
    commit: a59cafcb798d504a1b79c619ca87cfc82d3c5763
    directory: 3.11.2
    release:
      3-24.04:
        end-of-life: '2026-08-03T00:00:00Z'
        risks:
          - stable
      3.11-24.04:
        end-of-life: '2026-08-03T00:00:00Z'
        risks:
          - stable
