version: 2
application: alertmanager
description: |
  The Alertmanager handles alerts sent by client applications such as the
  Prometheus server. It takes care of deduplicating, grouping, and routing them
  to the correct receiver integrations such as email, PagerDuty, OpSGenie, or
  many other mechanisms thanks to the webhook receiver. It also takes care of
  silencing and inhibition of alerts.

website: https://prometheus.io/docs/alerting/latest/alertmanager/
issues: https://github.com/canonical/alertmanager-rock/issues
source-code: https://github.com/canonical/alertmanager-rock

docker:
  parameters: >-
    -p 9093:9093
  run_conclusion: |
    Alertmanager starts on port 9093.
    Access your Alertmanager instance at `http://localhost:9093`.

config:
  TZ:
    type: env
    description: Timezone.
    default: 'UTC'
  '`-v <path>:/etc/prometheus/alertmanager.yml`':
    type: mount
    description: Local configuration file alertmanager.yml.
  '`-v <path>:/alertmanager`':
    type: mount
    description: Persist data instead of initializing a new database for each newly launched container. The host data directory should belong to nogroup:nobody.
  '`-p <port>:9093`':
    type: port
    description: Expose port 9093 on the host.
