version: 2
upload:
  - source: canonical/alertmanager-rock
    commit: 7f5ef7760fe9e7d2d2fdf9d02e242ad8bb69269f
    directory: 0.32.0
    release:
      0-24.04:
        end-of-life: '2026-07-17T00:00:00Z'
        risks:
          - stable
      0.32-24.04:
        end-of-life: '2026-07-17T00:00:00Z'
        risks:
          - stable
