version: 2
upload:
  - source: canonical/alertmanager-rock
    commit: bcef65fcae0105e77f802a94f0610f96d156e3f8
    directory: 0.32.1
    release:
      0-24.04:
        end-of-life: '2026-08-10T00:00:00Z'
        risks:
          - stable
      0.32-24.04:
        end-of-life: '2026-08-10T00:00:00Z'
        risks:
          - stable
