version: 2
application: grafana
description: |
  Grafana is a feature rich metrics dashboard and graph editor for Cloudwatch,
  Elasticsearch, Graphite, InfluxDB, OpenTSB, Prometheus and Hosted Metrics.

  Please note that the images tagged up to 8.2 are Dockerfile-based images,
  whereas from version 10.0.3 onward the images are now rocks. As such the
  entrypoint is now Pebble.
website: https://grafana.com
issues: https://github.com/canonical/grafana-rock/issues
source-code: https://github.com/canonical/grafana-rock

docker:
  parameters: >-
    -p 3000:3000
  run_conclusion: |
    Access the Grafana web UI at `http://localhost:3000`.

config:
  TZ:
    type: env
    description: Timezone.
    default: 'UTC'
  '`-v <path>:/etc/grafana/provisioning/`':
    type: mount
    description: >-
      Directory to provision Grafana (see
      [documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/)).
  '`-v <path>:/var/lib/grafana`':
    type: mount
    description: >-
      Persist data with a volume instead of initializing a new database for
      each newly launched container.
  '`-p <port>:3000`':
    type: port
    description: Exposes the container's port `3000` on the host's `<port>`.
