version: 2
upload:
  - source: canonical/grafana-rock
    commit: 18997c736d56012bd97fb342a14e1f110a37f0a3
    directory: '12.4'
    release:
      12-26.04:
        end-of-life: '2026-12-28T00:00:00Z'
        risks:
          - stable
      12.4-26.04:
        end-of-life: '2026-12-28T00:00:00Z'
        risks:
          - stable
