version: 2
upload:
  - source: canonical/grafana-rock
    commit: a65643bcf59748779c1419adb831ad6e2e5c1e34
    directory: 12.4.2
    release:
      12-26.04:
        end-of-life: '2026-08-11T00:00:00Z'
        risks:
          - stable
      12.4-26.04:
        end-of-life: '2026-08-11T00:00:00Z'
        risks:
          - stable
