version: 2
upload:
  - source: canonical/grafana-rock
    commit: 222e4480aae6fabfe73330e93f2f1abb10156627
    directory: 12.4.4
    release:
      12-26.04:
        end-of-life: '2031-05-01T00:00:00Z'
        risks:
          - stable
      12.4-26.04:
        end-of-life: '2031-05-01T00:00:00Z'
        risks:
          - stable
