name: Artifact Crypto Handler
description: 'Encrypt and decrypt artifacts using GPG symmetric encryption'


inputs:
  mode:
    description: 'Operation mode: encrypt or decrypt'
    required: true
  input-path:
    description: 'Path where the artifact is stored'
    required: true
  passphrase:
    description: 'Passphrase for GPG symmetric encryption/decryption'
    required: true
  output-path:
    description: 'Path where the processed artifact should be stored (optional, defaults to input-path)'
    required: false
  preserve-original:
    description: 'Whether to preserve the original file after encryption/decryption (optional, defaults to false)'
    required: false

runs:
  using: "composite" 
  steps:

    - name: Cloning OCI Factory
      uses: actions/checkout@v4
      with:
        repository: canonical/oci-factory
        path: oci-factory
        fetch-depth: 1

    - name: Crypto Operation
      shell: bash
      id: crypto
      run: |
        ./oci-factory/.github/actions/crypt-artifact/crypt-artifact.sh ${{ inputs.mode }} \
          -i "${{ inputs.input-path }}" \
          -p "${{ inputs.passphrase }}" \
          -o "${{ inputs.output-path }}" \
          ${{ inputs.preserve-original == 'true' && '--preserve-original' || '' }}
