version: 2
application: traefik
description: |
  Traefik is a modern HTTP reverse proxy and load balancer that makes deploying
  microservices easy. Traefik integrates with your existing infrastructure
  components (Docker, Swarm mode, Kubernetes, Consul, Etcd, Rancher v2, Amazon
  ECS, ...) and configures itself automatically and dynamically.
website: https://traefik.io/
issues: https://github.com/canonical/traefik-rock/issues
source-code: https://github.com/canonical/traefik-rock

docker:
  parameters: >-
    -p 80:80
  run_conclusion: |
    Access the Traefik instance at `http://localhost:80`.

config:
  TZ:
    type: env
    description: Timezone.
    default: 'UTC'
  '`-v <path>:/etc/traefik/prometheus.yml`':
    type: mount
    description: Local configuration file for Traefik.
  '`-p <port>:80`':
    type: port
    description: Expose the container's port `80` on the host's `<port>` for HTTP connections.
  '`-p <port>:443`':
    type: port
    description: Expose the container's port `443` on the host's `<port>` for HTTPS connections.
