name: CLI-Client
on:
  push:
    paths:
      - "tools/cli-client/**"
  pull_request:
    paths:
      - "tools/cli-client/**"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Set up Go 1.22
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version: 1.22
      - name: Test
        working-directory: tools/cli-client
        run: |
          go test ./...

  build:
    runs-on: ubuntu-latest
    name: Snap build
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: snapcore/action-build@3bdaa03e1ba6bf59a65f84a751d943d549a54e79
        id: snapcraft
        with:
          path: tools/cli-client
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}
