name: CLI-Client
on:
  push:
    paths:
      - "src/cli-client/**"
  pull_request:
    paths:
      - "src/cli-client/**"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22
      - name: Test
        working-directory: src/cli-client
        run: |
          go test ./...
