name: CLI-Client
on:
  push:
    paths:
      - "tools/cli-client/**"
  pull_request:
    paths:
      - "tools/cli-client/**"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Set up Go 1.22
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492
        with:
          go-version: 1.22
      - name: Test
        working-directory: tools/cli-client
        run: |
          go test ./...

  build:
    runs-on: ubuntu-latest
    name: Snap build
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: snapcore/action-build@3bdaa03e1ba6bf59a65f84a751d943d549a54e79
        id: snapcraft
        with:
          path: tools/cli-client
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}
