name: builds
on:
  workflow_call:
    inputs:
      image:
        description: 'Path to the OCI image folder the builds.yaml file is'
        required: true
        type: string
      upload:
        description: 'If true, will upload/release the image to the registries'
        required: true
        type: boolean
        default: false

jobs:
  run-builds:
    runs-on: ubuntu-22.04
    name: Run builds for an image
    steps:
      - uses: actions/checkout@v3


