name: builds
on:
  workflow_dispatch:
  push:
    paths:
      - "oci/*/builds.y*ml"
  pull_request:
    paths:
      - "oci/*/builds.y*ml"

jobs:
  prepare-build-matrix:
    runs-on: ubuntu-22.04
    name: Prepare new builds
    outputs:
      images: ${{ steps.changed-oci-dirs.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed-oci-dirs
        uses: tj-actions/changed-files@v35
        with:
          json: true
          dir_names: "true"
          write_output_files: true
          files: |
            oci/*/builds.y*ml

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"

      - run: pip install -r src/builds/requirements.txt

      - name: Prepare builds matrix
        id: prepare-builds
        run: |
          ./src/builds/prepare-multi-image-build-matrix.py \
            --oci-dirs-file ".github/all_changed_files.json"

  run-builds:
    runs-on: ubuntu-22.04
    needs: [prepare-build-matrix]
    name: Build
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare-build-matrix.outputs.build-matrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: matrix.build.source
          ref: matrix.build.commit
          path: "source-repo"

      - name: Build ROCK
        if: matrix.build.source-type == 'rockcraft'
        uses: canonical/craft-actions/rockcraft-pack@main
        with:
          path: "source-repo/${{ matrix.build.directory }}"
          verbosity: debug
