name: builds
on:
  workflow_call:
    inputs:
      image:
        description: 'Path to the OCI image folder the builds.yaml file is'
        required: true
        type: string
      upload:
        description: 'If true, will upload/release the image to the registries'
        required: true
        type: boolean
        default: false

jobs:
  prepare-builds:
    runs-on: ubuntu-22.04
    name: Prepare builds
    outputs:
      build-matrix: ${{ steps.prepare-builds.outputs.build-matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: Prepare build matrix
        working-directory: ${{ inputs.image }}
        id: prepare-builds
        run: | 
          pip install yq
          echo "build-matrix={\"build\":\"$(cat builds.yaml | yq -c .images)\"}" >> "$GITHUB_OUTPUT"

  run-builds:
    runs-on: ubuntu-22.04
    needs: [prepare-builds]
    name: Build
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare-builds.outputs.build-matrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: matrix.build.source
          ref: matrix.build.commit





