name: builds
on:
  workflow_dispatch:
    inputs:
      oci-image-name:
        description: 'Name of the OCI image to to run the builds for'
        required: true
  push:
    paths:
      - "oci/*/builds.y*ml"
  pull_request:
    paths:
      - "oci/*/builds.y*ml"

jobs:
  prepare-build-matrix:
    runs-on: ubuntu-22.04
    name: Prepare new builds
    outputs:
      build-matrix: ${{ steps.prepare-builds.outputs.build-matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: Infer images to build
        if: github.event_name != 'workflow_dispatch'
        uses: tj-actions/changed-files@v35
        with:
          json: true
          dir_names: "true"
          write_output_files: true
          files: |
            oci/*/builds.y*ml

      - name: Validate images from dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          test -d "oci/${{ inputs.oci-image-name }}"
          mkdir -p .github/outputs
          echo '["oci/${{ inputs.oci-image-name }}"]' > .github/outputs/all_changed_files.json

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - run: pip install -r src/builds/requirements.txt

      - name: Prepare builds matrix
        id: prepare-builds
        run: |
          ./src/builds/prepare-multi-image-build-matrix.py \
            --oci-dirs-file ".github/outputs/all_changed_files.json"

  run-builds:
    runs-on: ubuntu-22.04
    needs: [prepare-build-matrix]
    name: Build
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare-build-matrix.outputs.build-matrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: matrix.source
          ref: matrix.commit
          path: "source-repo"

      - name: Build ROCK
        if: not matrix.dockerfile-build
        uses: canonical/craft-actions/rockcraft-pack@main
        with:
          path: "source-repo/${{ matrix.build.directory }}"
          verbosity: debug
