name: CLA Check
on: [pull_request]

jobs:
  cla-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v1
        with:
          # This is to avoid failing the checks for ROCKsBot
          accept-existing-contributors: true