name: Continuous image testing

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  prepare-test-matrix:
    runs-on: ubuntu-latest
    name: Prepare released image revisions to be tested
    outputs:
      released-revisions-matrix: ${{ steps.prepare-test-matrix.outputs.released-revisions-matrix }}
      last-scan: ${{ steps.last-scan.outputs.date }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: pip install -r src/tests/requirements.txt

      - name: Fetch _releases.json
        uses: ./.github/actions/fetch-releases-json
        with:
          image-name: '*'
          releases-branch: "_releases"

      - name: Prepare test matrix
        id: prepare-test-matrix
        run: python3 -m src.tests.get_released_revisions --oci-images-path $PWD/oci

      - name: Infer date of last scan
        id: last-scan
        run: |
          # This is scheduled to run every day, so let's look at the previous
          # 26 hours, roughly
          set -e
          if [[ "$RUNNER_DEBUG" == "1" ]]; then
            set -x
          fi
          last_scan="$(date --date='26 hours ago' +'%Y-%m-%dT%H:%M:00Z')"
          echo "date=$last_scan" >> "$GITHUB_OUTPUT"

  run-tests:
    name: Run tests for released images
    needs: [prepare-test-matrix]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare-test-matrix.outputs.released-revisions-matrix) }}
    uses: ./.github/workflows/Vulnerability-Scan.yaml
    with:
      oci-image-name: "${{ matrix.source-image }}"
      oci-image-path: "oci/${{ matrix.name }}"
      trivyignore-path: "oci/${{ matrix.name }}/.trivyignore"
      date-last-scan: ${{ needs.prepare-test-matrix.outputs.last-scan }}
      create-issue: true
    secrets: inherit
